### ISSUE TITLE
Geen gebruik gemaakt van custom properties in css

### ISSUE THREAD

**Issue by SuleymanHG** [Nawallox/look-and-feel-corporate-identity#13]
Je hebt geen custom properties in je [css ](https://github.com/Nawallox/look-and-feel-corporate-identity/blob/main/styles.css)gebruikt, die kan je even toevoegen.

@SuleymanHG, @rickFDND, @nyathene

**Comment by Nawallox** [comment]
Ik heb een :root met custom properties in de css toegevoegd
