### ISSUE TITLE
Is deze kleur ook terug te vinden in de gezamenlijke styleguide?

### ISSUE THREAD

**Issue by suustenvoorde** [Nawallox/look-and-feel-corporate-identity#18]
Je maakt gebruikt van de kleurcode `#5c104e`, maar deze is niet terug te vinden in de gezamenlijke styleguide. Gebruik kleuren uit de styleguide op deze manier bijvoorbeeld: var(--primary-color). Zo maak je gebruik van de custom properties uit de gezamenlijke styleguide.

https://github.com/Nawallox/look-and-feel-corporate-identity/blob/81cb99e8fcb1fa098da285575434475ee3259354/styles.css#L13

**Comment by Nawallox** [comment]
Ik heb de : root aangepast van mijn CSS, zoals de gezamenlijke styleguide, zodat de kleuren ook overheen komen met elkaar

**Comment by suustenvoorde** [comment]
Volgens mij wil je de kleuren niet in het CSS bestand toevoegen van jouw eigen repo, maar wil je de kleuren gebruiken uit de gemeenschappelijke styleguide. Deze issue zou ik opnieuw openen en op een andere manier oplossen.
